name: chest
description: CHEck STrings - a tool to find files, filter strings and optionally check matches
version: 0.1.1
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/chest/

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  async: ^2.11.0
  file: ^6.1.4
  file_ext: ^0.6.1
  get_it: ^7.2.0
  glob: ^2.0.2
  loop_visitor: ^0.3.0
  parse_args: ^0.13.1
  path: ^1.8.3
  thin_logger: ^0.2.0
  utf_ext: ^0.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
