name: chest
description: CHEck STrings - a tool to find files, filter strings and optionally check matches
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  args: ^2.3.0
  file: ^6.1.2
  glob: ^2.0.2
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
