name: chest
description: CHEck STrings - a tool to find files, filter strings and optionally check matches
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  async: ^2.10.0
  file: ^6.1.2
  file_ext: ^0.2.1
  get_it: ^7.2.0
  glob: ^2.0.2
  parse_args: ^0.11.0
  path: ^1.8.1
  thin_logger: ^0.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
